### PR TITLE
Add support for gathering proc files necessary to convert coredump to minidump

### PR DESCRIPTION
**Pull request by swermin**
Running breakpads core2md out-of-process requires some files from the /proc/$pid folder to be able to successfully generate enough information.
This change enables gathering of those said files to be able to support that flow. It is hidden behind a feature flag and its disabled by default so that the behavior of the composer is same as before.

This feature is ment to grab the minimum files needed to be able to generate minidumps. So heap data will be omitted and such.

### CODE REVIEW

**Comment by No9** [comment]
@swermin quick update to let you know I'll get to the review over the next few days. 
I want to land this for the next release which I'm planning for the 9th.

**Comment by swermin** [comment]
Sounds great, I am available anytime to answer and makes changes as needed!

**Comment by usimd** [comment]
Hey @No9! Not meaning to pressure, just kindly wanted to ask if it would be possible to proceed here in order to get a new release (eagerly waiting for https://github.com/IBM/core-dump-handler/pull/160 :stuck_out_tongue:)

**Comment by No9** [comment]
Thanks for the nudge @usimd 
I'm external to IBM now so I've just requested @jjasghar to set me up with the right permissions to accept this.
FWIW this is close to a LGTM but I want to test it before release.

**Comment by No9** [comment]
Update - Looks like I'm back as repo admin - Thanks @jjasghar 
I'll look at this ASAP.

**Comment by swermin** [comment]
Hi @No9, have you had a chance to go through these changes? 😄

**Review by No9 — APPROVED** [review]

**Comment by No9** [comment]
Thanks for the reminder - been very busy for the past few weeks. 
I'll wait to see if we can get this other one in and do a release.
https://github.com/IBM/core-dump-handler/pull/162#pullrequestreview-2228995725

**Pull request merged**
