### PR TITLE
Add pod annotations

### PR DESCRIPTION
**Pull request by binarysta**
to address https://github.com/IBM/core-dump-handler/issues/161

### CODE REVIEW

**Review by No9 — COMMENTED** [review]
Thanks for this 
Can you update the daemonset notes in the readme 
https://github.com/IBM/core-dump-handler/blob/main/charts/core-dump-handler/README.md and rebase onto main and I will merge and do a release.

**Comment by binarysta** [comment]
Thanks for reviewing. I updated the PR.

**Review by No9 — APPROVED** [review]

**Comment by No9** [comment]
Approved but can you resign the commit to pass the DCO test please

**Comment by binarysta** [comment]
thanks. signed off.

**Comment by No9** [comment]
Thanks again for coming back so soon

**Pull request merged**
