### PR TITLE
Use error logger in timeout condition

### PR DESCRIPTION
**Pull request by timbuchwaldt**

### CODE REVIEW

**Comment by No9** [comment]
You've probably realized `error!` goes to std.err not std.out. 
Don't forget to sign it so the DCO passes. 
I want to get my patch to log4rs in the next release of CDH too https://github.com/estk/log4rs/commit/1b988edd87c47d1c85afe4af8dee0aff38254456 
so I'll publish this as soon as you're ready.

**Comment by timbuchwaldt** [comment]
Sorry about the dealy, there you go :)

**Comment by No9** [comment]
Hey @timbuchwaldt The test for timeout is failing now. Can you take a look when you have a minute.

**Comment by No9** [comment]
Hey @timbuchwaldt January house keeping :) 
Is this still WIP or should we close it?

**Comment by No9** [comment]
Hey @timbuchwaldt - Thanks for coming back to this. 
Do you want to land this now it's passing?

**Review by No9 — APPROVED** [review]

**Pull request merged**
